{% set version = "1.1" %}
{% set sha256 = "04b297f68a10db4fa40edf68d7f823ba7b9d0442f2b665181889abe2cea42759" %}

package:
  name: libspnav
  version: {{ version }}

source:
  url: https://github.com/FreeSpacenav/libspnav/releases/download/v{{ version }}/libspnav-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - autoconf
    - automake
    - libtool
    - m4
    - make  # [unix]
  host:
    - xorg-libx11 =1.8.4
  run:
    - xorg-libx11

test:
  commands:
    - test -f $PREFIX/lib/libspnav.a  # [linux]
    - test -f $PREFIX/lib/libspnav.so.0  # [linux]
    - test -f $PREFIX/lib/libspnav.dylib  # [osx]

about:
  home: http://spacenav.sourceforge.net/
  doc_url: http://spacenav.sourceforge.net/
  dev_url: https://github.com/FreeSpacenav/libspnav
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The libspnav library is provided as a replacement of the magellan library.
  description: |
    The libspnav library is provided as a replacement of the magellan library.
extra:
  recipe-maintainers:
    - looooo
